# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

coins = Coin.create([
    { name: 'Dólar Americano', code: 'USD', symbol: '$', country: 'Estados Unidos',
      url_name: 'dolar-americano', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/us.svg', 
      story: 'O dólar americano é a moeda oficial dos Estados Unidos da America e dos territórios regidos pela constituição estadunidense. Inicialmente durante os séculos 16 e 18 o dólar americano era baseado no valor do dólar espanhol (o império espanhol era um dos maiores na época). Após a independência das 13 colônias os americanos estavam livres para usar outra moeda além da libra esterlina. Durante o século 18 e 19 o dólar americano flutou de acordo com o valor da prata e em seguida de acordo com o valor do ouro. Logo após a segunda guerra mundial foi díficil determinar o verdadeiro valor do dólar, o governo americano realizou o tratado de Bretton Woods que decidiu então fixar o valor de um onça (equivale a 28,3495 gramas de ouro), assim o dólar variava de acordo com o valor do ouro. Ao longos dos anos seguintes as reservas americanos de ouro diminuiram bastante e o sistema de Bretton Woods durou até a década de 70 quando surge o câmbio com maior flutuação devido as novas tecnologias da época. Em 1979 Paul Volcke foi nomeado presidente da Reserva Federal Americana, seus esforços para controlar a inflação do dólar tiveram resultados expressivos e em 1980 a moeda americana estava estabilizada. Durante os 30 anos seguintes 1981 a 2009, o dólar dos EUA perdeu mais da metade do seu valor, apesar de ser uma grande perda a moeda americano conseguiu resultados muito bons, como por exemplo um inflação de apenas 2% na década entre anos de 1997 e 2007. Atualmente é a moeda mais comercializada do mundo, sendo que dois terços do dólares existentes estão fora dos EUA.' },  
    
    { name: 'Euro', code: 'EUR', symbol: '€', country: 'União Europeia',
      url_name: 'euro', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/eu.svg', 
      story: 'O Euro é a moeda oficial da União Europeia (UE) que compõe a chamada zona do Euro, sendo que dos 28 paises que fazer parte UE 19 já adotaram o euro como moeda oficial do país, sendo eles: Alemanha, Áustria, Bélgica, Chipre, Eslováquia, Eslovénia, Espanha, Estónia, Finlândia, França, Grécia, Irlanda, Itália, Letónia, Lituânia, Luxemburgo, Malta, Países Baixos e Portugal. O Euro se destaca também pelo seu valor atrativo (maior que o dólar americano) e também por ser a segunda maior moeda de reserva e a segunda moeda mais transações no mundo. A ideia do Euro surgiu em dezembro de 1995 e depois de consolidada a moeda foi inserida no mercado no primeiro dia do ano de 1999 para substituir a antiga Unidade Monetária Europeia. A moedas e notas entraram em circulação apenas em 2002. A menor cotação já registrada do euro foi de 0,8252 US $ em 2000 e maior foi de 1,6038 US $ em julho de 2008 durante a crise americana, a partir de então o dólar voltou ao seu valor "estável" e a União Europeia tem trabalhado para manter o euro também estável. Apesar de sua forte presença e importância no mercado mundial o Euro corre o risco de deixar de existir, em 2011 por exemplo esse foi um assunto abordado em vários parlamentos europeus.' },

    { name: 'Lira Esterlina', code: 'GBP', symbol: '£', country: 'Reino Unido',
      url_name: 'libra-esterlina', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/gb.svg', 
      story: 'A Libra Esterlina é a moeda oficial do Reino Unido, ela é dividida em 100 pence. A origem dessa moeda vem desde o período pŕe-medieval, na inglaterra anglo-saxônica, na qual uma libra daquela época era igual a 240 centavos de prata. O centavo dep prata foi introduzido no mercado pela primeira vez no reinado do rei Offa de Mercia (757-796 d.c). As primeiras moedas eram feitas de prata pura, fato que mudou a partir de 1158 no reinado de Henry || onde as moedas era feitas apenas com 92% de prata. A unificação do Reino Unido é um episódio importante na história da moeda desse reino, em 1707 o Reino da Inglaterra se une ao Reino da Escócia e formam o reino da Grã-Bretanha, esse novo reino adotou a moeda do antigo reino inglês. Já em 1801 o Reino de Grã-Bretanha se une com o Reino da Irlanda para formar o Reino Unido da Grã-Bretanha e da Irlanda, entretanto nesse mais novo reino as duas moedas dos reinos antigos continuaram em circulação, não houve predominância de uma delas. Nos séculos 18 e 19 com a independência das colônias inglesas a libra aos poucos perdeu espaço ao redor do mundo e foi ganhando espaço no próprio reino, deixando a libra irlandesa cada vez menos utilizada. Depois da segunda grande guerra a libra esterlina foi se desvalorizando cada vez mais em relação ao dólar, o próprio governo por questões estratégicas chegou a desvalorizar a moeda em até 30%. Nos primeiros 40 anos pós guerra a libra perdeu metade do seu valor em relação ao dólar, o tratado de Bretton Woods que fixou o dólar em relação a libra contribuiu para essa desvalorização. Com o fim dessa tratato em 1971 a libra voltou a flutuar seu valor de acordo com a margem estabelecida pelos britânicos. em 1976 a econômia britânica passou por grise interna devido a crise do pétroleo de 1973, a inflação no Reino Unido chegou a 27% em 1975, com isso o mercado externo começou a acreditar que a libra estava sobrevalorizada, assim os investimentos ingleses estavam sempre mais caros do que deveriam ser o que fez com o que o reino criasse uma dívida externa que posteriormente foi controlada com a ajuda do FMI. Atualmente como o Reino Unido faz parte da União Europeia ele poderia ter adotado o euro porém por questões políticas e populares não o fez. Em janeiro de 2008 a República de Chipre foi a primeira sobre a soberania da Grã-Bretanha a trocar sua moeda local (libra chipriota) pelo euro, em seguida as bases soberanas britânicas sobre Chipre (Akrotiri e Dhekelia) seguiram o seu exemplo se tornando as Áreas da Soberana Base o único território sob soberania britânica a utilizar oficialmente o euro. Por fim o referendo de 2016 que resultou na saída do Reino Unido da União Européia tornou quase impossível a adoção do euro' },  

    { name: 'Yuan Renminbi', code: 'CNY', symbol: '¥', country: 'China',
      url_name: 'china-yuan-renminbi',
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/cn.svg', 
      story: 'Yuan Renminbi é moeda oficial da China (ou República popular da China), a moeda é distribuída pelo Banco Popula da China. O Yuan Renmibi foi apresentado pela primeira vez em 1949, e a partir de 1970, quando a econômia da China começou seu expansão (se tornando a segunda maior econômia do mundo) a moeda se popularizou.
        Nos anos 70 ela atigiu seu maior valor, chegando valor 1.50 ¥ = 1 $. A partir de então o valor da moeda vem caindo.' },

    { name: 'Lira Turca', code: 'TRY', symbol: '₺', country: 'Turquia', 
      url_name: 'lira-turca',
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/tr.svg', 
      story: 'A moeda turca tem um ciclo de vida divido em duas fases, em sua primeira fase de 1923 - 2003. Avaliada em ₺ 2.8 = $ 1 Dólar Americano no ano de 1946, ela se manteve mais ou menos estável até 1966, ano no qual 9 Liras = 1 Dólar. A partir desse ano a inflação atingiu em cheio a moeda e em 2001 $ 1 Dólar Americano comprava 1.650.000 Liras Turcas.
      A segunda fase da moeda é um tanto confusa, o governo e o banco turco lançaram a nova moeda, chamada de Nova Lira Turca abrevida como YTL, que valia 1.00.000 (um milhão) da antiga Lira Turca, removendo assim 6 zeros da moeda inflacionada. A transação da mova moeda durou de 2005 - 2008. Porém em 2009, ano no qual a o período de transação acaba, a Nova Lira Turca e renomeada para Lira Turca novamente com a abreviação TL, embora muitos países ainda utilizem a antiga abreviação TRY. Essa recuperação da moeda tem dado certo até agora, em 2005 $ 1 Dolár Americano = 1.29 Liras Turcas, e em 2016 a moeda ainda apresenta um valor estável, $ 1 US = ₺ 3.44 TRY.' },

    { name: 'Peso Mexicano', code: 'MXN', symbol: 'Mex$', country: 'México',
      url_name: 'peso-mexicano', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/mx.svg', 
      story: 'Velho Peso: No século 19 durante o império Espanhol o peso era o nome dado as oito peças de oito, que eram oito moedas reais imitidas pela Espanho no México. As primeiras moedas surgiram apenas em 1863, quando começou-se a atribuir o nome de "um peso" para a moeda mexicana (um peso  = 100 centavos de moedas). Como algumas moedas eram realmente emitidas em prata, no começo do século 20 (1905) a moeda começa a sofrer uma desvalorização devido a desvalorização da prata em si.
        
        Novo Peso: Já mais a frente no século 20 (1920) o peso mexicano se mantém como umas das moedas mais estáveis da america latina pois o país não enfrentava perídos de super inflação como seus vizinhos enfrentavam. Entretando durante a crise do petróleo nos anos 70 não conseguiu pagar seu dívida externa deixando as contas do país no vermelho, isso fez com que muitos investidores saíssem do país, ou seja, mais capital indo embora, tudo isso resultou em anos de inflação no país e de desvalorização da moeda. Em 1º de janeiro de 1993 o governo cria uma nova estratégia econômica chamada de PECE (Pacto da Estabilidade e Crescimento Econômico) na qual é introduzido no país o novo peso mexicano, entitulado como N$. Definindo então que N$ 1 = 1000 pesos antigos. A partir de então o México conseguiu manter uma estabelidade econômica respeitável e hoje seu moeda está entre as 15 mais negociadas no mundo.' },

    { name: 'Roblo Russo', code: 'RUB', symbol: '₽', country: 'Rússia',
      url_name: 'roblo-russo', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/ru.svg', 
      story: 'O Roblo Russo é a segundo moeda mais antiga que se mantém atualmente, usada nos territórios russos desde o século 13. Antigamente denomida apenas como Roblo, foi a moeda usada no império Russo (1721-1917) e também na União Soviética (1922-1991). Uma curiosidade interessante é que o Roblo foi a primeira moeda a ser dividida em centavos (₽ 1 = 100 kopeks). Durante a União Soviética o Roblo foi renomeado para Roblo Soviético (sigla: SUR), um ano depois do fim desse período, ou seja, em 1992, o Roblo Soviético foi renomeado para Roblo Russo (sigla: RUR), nome que permanece até hoje. Por fim em 1998 durante um período de crise na Rússia a moeda russa ganha uma nova sigla, RUB e uma nova taxação na qual 1 RUB = 1000 RUR. Desde então a moeda se mantém sem grandes alterações.' },

    { name: 'Dólar de Hong Kong', code: 'HKD', symbol: 'HK$', country: 'Hong Kong',
      url_name: 'dolar-de-hong-kong', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/hk.svg', 
      story: 'Uma moeda com uma história mais curta, a moeda de Hong Kong começa a ser emetida a partir de 1863 pelo rei britanico que reinava o país colono na época, essa emissão dura até 1992. A partir de 1993 uma nova emissão seguindo o desenho da flor de baunilha (presente também na bandeira do país) começa a ser a nova moeda, substituindo as moedas estampadas com o resto da rainha Elizabeth 2º. Hoje as duas moedas ainda são utilizadas no país.' },

    { name: 'Ringgit Malaio', code: 'MYR', symbol: 'RM', country: 'Malásia',
      url_name: 'malasia-ringgit-malaio', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/my.svg', 
      story: '' },

    { name: 'Baht', code: 'THB', symbol: '฿', country: 'Tailândia', 
      url_name: 'tailandia-baht',
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/th.svg', 
      story: 'A moeda tailandesa, assim como a libra esterlina, teve origem a partir de uma unidade de massa, seu valor de origem era representado pelo seu peso em prata (15 gramas), ou seja, uma moeda valia o 15 gramas de prata. Voltando um pouco mais no tempo, durante o período Sukhothai (1238-1438) a moeda na Tailândai era chamada de "phot duang".  Eram pedaços de prata e o peso de cada pedaço possuia seu valor monetário, Bath é o nome de um valor específico entre os pedaços (cada um possuia um nome). Esse sistema de moedas baseado no peso e no valor da prata foi utilizado até 1897 quando Jayanta Mongkol inventou um sistema decinal para o país no qual 1 bath = 100 Satang, esse novo sistema foi abraçado pelo rei Chulalongkorn (1868-1910). A notação Bath não sofrou mudanças em seu nome e como sempre foi baseada no valor da prata também não sofreu uma nova taxação do governo para recuperar a desvalorização da moeda durante a crise asiática (1997), ao longo dos anos ela simplesmente sofre algumas fixações, por exemplo durante a segunda guerra mundial o valor de 11 Bath foi fixado à 1 Iene japonês.' },

    { name: 'Złoty', code: 'PLN', symbol: 'zł', country: 'Polônia',
      url_name: 'polonia-zloty', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/pl.svg', 
      story: 'A moeda da Polônia, "Złoty", significa ouro e atualmente 1 zł e dividido em 100 groszy. Voltando um pouco mais na história, muito antes do Złoty a moeda polonesa era a Grzywna que valia 210 gramas de prata, utilizada até o século 14 quando foi substituida pela Kraków grzywna que valia 198 gramas de prata. A história dessa moeda é dividida em quatro fases. A primeira fase começa ainda na idade média, nos séculos 14 e 15 ... Falar das outras fases... Atualmente a moeda polonesa enfrenta um impase, com a entrada da Polônia na União Européia em Maio de 2004 o país é obrigado a aderir o euro como moeda oficial (uma das condições impostas para que o país fosse aceito na UE) entretanto a contituição Polonesa protege o Złoty como moeda oficial até 2019, ou seja, antes disso é muito provável que o euro não seja aceito no país. Outro impase que surge é entre a própria população que segundo uma pesquisa de 2011, realizada pela CBOS, 60% dos poloneses são contra a adesão do euro e apenas 32% é a favor' },

    { name: 'Dólar Canadense', code: 'CAD', symbol: '$', country: 'Canadá',
      url_name: 'dolar-canadense', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/ca.svg', 
      story: 'O Dolar Canadense ocupa a quinta posição entre as moedas mais mantidas do mundo (em volume), ficando apenas atrás do Dólar Americano, Euro, Iene e da Libra Esterlina. Isso se deve ao fato do Canadá ser um país com a economia sólida, establidade política e IDH alto, essa é a receita mais comum entre as moedas mais sólidas da atualidade. A história dessa moeda começa ainda com o Canadá como província, em 1841, adotou um novo sistema de monetário no qual a nova libra canadense valia 4 dólares americanos (93 grãos de ouro). Entretanto em 1850 a população percebeu que era preciso sair desse antiguado sistema monetário e se adequar aos mais atuais como libra esterlina ou ao sistema decimal do Dólar Americano. Devido a proximidade cada vez maior com os vizinhos americanos, os canadenses decidiram adequar sua moeda colonial ao Dólar Americano, porém nem tudo são flores, as autoridades imperiais do Reino Unido preferem a moeda esterlina como moeda única em todo o império Inglês. Por fim em 1853 a administração canadense adotou um padrão-ouro que atenderia em parte o padrão britânico e o padrão americano ao mesmo tempo. Em 1858 a província do Canadá começa a emetir moedas de bronze (1¢) e moedas de prata (10¢ e 20¢), a mudança vem em 1870 quando a moeda de bronza para de ser produzida e surgem as novas moedas de 25¢ e 50¢. Entretanto apenas em 1908 - 1912 o Canadá começa a emetir suas primeiras moedas de dólares de ouro' },

    { name: 'Pataca', code: 'MOP', symbol: 'MOP$', country: 'Macau',
      url_name: 'macau-pataca', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/mo.svg', 
      story: 'Em 1894 a a nomenclatura Pataca é introduzida em Macau, a pataca correspondia ao dolár mexicano e tinha um valor de 1 pataca = 450 reais, essa medida tinha como objetivo substituir o real português. O nome pataca se deve ao fato dos portugueses chamarem o dólar mexicano de pataca mexicana. Mesmo com essa medida ainda no século 19 existiam diversas moedas circulando em Macau (dólares mexicano e britânico). Finalmente em 1901 foi decidido que Macau deveria ter apenas uma única moeda em circulação dentro do país, o Banco Nacional Ultramarinho (fundado em Lisboa) ficou com os direitos para a emissão de moedas/notas denominadas Patacas. No ano de 1906 as primeiras notas de 1, 5, 50 e 100 são inauguradas no mercado e as demais moedas foram proibidas. Nos anos 50 a moeda oscilou ora de acordo com o valor da prata e ora de acordo com o valor do ouro. Somente em 1980 o Instituto Emissor de Macau (criado pelo governo de Macau) conseguiu o direito de emitir as patacas. O Banco Nacional Ultramarinho se tornou agente do IEM e continuou a emitir as patacas até o ano de 1995, quando o a lisença para emissão das patacas é transferida para a Autoridade Monetária de Macau e o ramo de Macau do banco da China se torna o segundo emissor oficial das patacas.' },

    { name: 'Won', code: 'KRW', symbol: '₩', country: 'Coréia do Sul',
      url_name: 'won-coreia-do-sul', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/kr.svg', 
      story: 'A moeda sul Coreana Won é dividida em 100 jeon que curiosamente não utilizado em transações no dia a dia dos sul-coreanos. O Banco da Coreai é o atual emissor do Won e fica sediado em Seul, capital do país. A história dessa moeda começa pouco depois da era colonial, quando o país ainda adotava o Iene japonês como moeda oficial, depois de segunda guerra mundial (1945) o país dividido em sul e norte possuia duas moedas chamadas won, Won do Sul e Won do Norte, substituindo de vez o Iene japonês. O Won do Sul foi inicialmente vinculado ao dólar americano, entretanto a moeda sempre esteve bem desvalorizada, em 1945 15 wons = 1 dólar. Apenas 6 anos depois, em 1951 6000 wons = 1 dólar' },

    { name: 'Iene', code: 'JPY', symbol: '¥', country: 'Japão',
      url_name: 'japao-iene', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/jp.svg', 
      story: 'O Iene é a moeda oficial do Japão e também a terceira moeda mais comercializada no mundo, é a reserva financeita mais usada no mundo, somente atrás do dólar americano, do euro e da libra esterlina. Começamos com a história do Iene a partir da segunda guerra mundial, em Abril de 1949 durante a ocupação americano no japão (período pós guerra) o preço do Iene foi fixado em ¥ 360 = $ 1. A ideia de fazer com o que a moeda japonesa fosse subvalorizada (baixo valor de mercado em relação as outras moedas) teve seu primeiro reflexo em 1971 quando o país saiu do saldo negativo para um saldo positivo de 5,8 bilhões de dólares, mas como? O país que tem como foco a exportação desvalorizou a própria moeda para conseguir exportar com preços mais atrativos em relação aos seus concorrentes em contra mão a importação fica mais cara para os japoneses entretanto a conta final resultou em um saldo positivo para o país. Nos anos 80 o governo e os empresários japoneses incentivaram fortemente na desvalorização da moeda pois ambos tinham medo que a valorização imposta pelo mercado extrangeiro afetasse as exportação do país. Os esforços duraram até 1985 quando as autoridades financeiras de grandes economias assinaram o Acordo de Plaza que rotulavo o dólar americano como sobrevalorizado e o Iene como subvalorizado, como solução para esse problema as pressões internacionais conseguiram elevar o valor do Iene e o mesmo atingiu seu pico em 1995 quando ¥ 80 = 1 $. Nesse ano a economia do Japão era quase do mesmo tamanho dos EUA. Depois da crise de 2008 as principais moedas do mundo entraram em desvalorização em relação ao Iene fato que afeta negativamente as exportações do país. Por esse motivo até 2013 o governo japonês tem dedicado seus esforços para desvalorizar o Iene novamente.' },

    { name: 'Grívnia Ucraniana', code: 'UAH', symbol: '₴', country: 'Ucrânia',
      url_name: 'grivnia-ucraniana', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/ua.svg', 
      story: 'Grívnia é a moeda nacional da Ucrânia desde setembro de 1996, sendo que uma Grívnia é dividida em 100 kopiyky. Chamada de Keiven Rus quando ainda era colônia da Rússia a atual Ucrânia se declarou independente em 1917 e a sua moeda foi renomeada para Grívnia. De 2 a 16 e setembro a nova moeda substituiu a antiga (que estava hiperinflacionada da antiga União Soviética) por uma escala de 1 para 100.000. Um fato curioso é que a inserção da nova moeda no mercado foi bem rápida. No período de 2 a 16 de setembro o governo forçou os comerciantes a colocarem a nova moeda em circulação e todas as contas bancárias foram atualizadas automaticamente, assim no dia 16 de setembro 97% das moedas em circulação já eram Grívnia. Desde de então a única mudança que essa moeda sofreu foi na região da Crimeia que foi anexada pela Rússia no dia 18 de março de 2014, sendo assim nessa região a Grívnia foi substituida pelo roblo-russo.' },

    { name: 'Florim Húngaro', code: 'HUF', symbol: 'Ft', country: 'Hungria',
      url_name: 'florim-hungaro', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/hu.svg', 
      story: 'Florim Húngaro é a moeda oficial de Hungria, 1 florim é divido em 100 fillér, entretanto as moedas (centavos de florim) não se encontram mais em circulação no país. O nome florim vem da cidade de Florença na Itália pois em 1252 era lá que as moedas de ouro eram mineradas. Entre os anos de 1868 e 1892 Florim foi o nome usado na moeda oficial do império Austro-Húngaro, depois disso o florim deu espaço para outras que entraram em circulação no império. Foi inserido no país em agosto de 1946 depois que a moeda da epóca atingiu a maior hiperinflação já registrada. A partir dai a moeda se manteve estável ao longo dos anos, sofreu um pouco com o fim da União Soviética nos anos 80, chegando a inflacionar cerca de 35% ao ano, entretante o governo mantém reformas e medidas em dia para estabalizar a moeda.' },

    { name: 'Dólar de Singapura', code: 'SGD', symbol: 'S$', country: 'Singapura',
      url_name: 'dolar-de-singapura', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/sg.svg', 
      story: 'O dólar de Singapura é a moeda oficial do país, e um dólar é dividido em 100 centavos. Em 2016 o dólar de Singapura foi a 12º moeda mais negociada no mundo. Entre os anos de 1845 e 1939 duas moedas foram utilizadas antes do dólar de Singapura, o dólar Malaio e o dólar Estreito. Somente após a independência de Singapura da Malásia em 1965 foi criado o Conselho de Comissários de Moeda e a partir de abril de 1967 o país emitiu suas primeiras moedas e notas. Nos anos 70 o Parlamento de Singapura aprovou a Autoridade Monetária da Lei de Singapura em 1970, levando à formação do MAS (Autoridade Monetária de Singapura), o MAS era responsável por verificar se o dólar de Singapura flutuava dentro de uma margem aceitável (uma margem definida por eles mesmos que era mantida em segredo). Em 2003 o MAS se uniu com o  Conselho de Comissários de Moeda Cingapura para se tornarem um só e assim assumir a responsáblidades pelas notas e moedas do país.' },

    { name: 'Kuna Croata', code: 'HRK', symbol: 'kn', country: 'Croácia',
      url_name: 'kuna-croata', 
      flag: 'https://lipis.github.io/flag-icon-css/flags/4x3/hr.svg', 
      story: 'Kuna é a moeda oficial da Croácia, ela é emitida pelo Banco Nacional Croata e mantida pelo Instituto Monetário Croata, uma Kune é dividida em 100 lipas. A palavra Kuna significa marten (no português marta, uma categoria de mamífiros que possui uma pele valiosa no mercado da moda). O Kuna moderna foi introduzida no país em Maio de 1994, o período de transação durou até o dia 31 de Dezembro do mesmo ano. Por ser uma moeda muito nova ela não sofreu nenhuma mundança drástica até agora, ao longo dos anos o governo Croata apenas tenta manter um valor estável para a moeda em relação ao valor do euro. A grande mudança que o a país espera é devido a adesão à União Europeia em julho de 2013, sendo assim a Kuna provavelmente será substituida pelo euro nos próximos anos, uma vez que o governo não mostrou nenhum objeção contra a adoção do euro como moeda nacional.' }          
  ])
